version: "3.8"
services:
  name-generator-mockservice:
    build:
      context: ./ContainerCanary/NameGeneratorMockService
    image: container-canary-mockservice:latest
    ports:
      - "5002:80"

  canary-api:
    build:
      context: ./ContainerCanary/Canary-API
    image: container-canary-api:latest
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MOCK_SERVICE_URL=http://name-generator-mockservice:80